name: Paolo Delfino
favicon: null
layout_spectrum: 0.7898150933906436
typography_spectrum: 0.3079509465023875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3326205560006201
  lightness: 0.0625655697658658
  saturation: 0.06698309467174113
  rhythmicContrast: 0.5012002538423985
purpose: []
